M48
; DRILL file {KiCad (6.0.5)} date Tue Oct  4 21:38:20 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-04T21:38:20-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X-66.8Y2.4
X-29.15Y-9.55
X-29.09Y28.59
X9.0Y28.6
X9.3Y-31.52
X40.23Y-63.82
T0
M30
